/** @type {import('tailwindcss').Config} */

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#4648d4",
        surface: '#fcf8ff',
        indigo: "#4648d4",
        indigoDark: "#3730a3",
        cyan: "#06b6d4",
        bg: "#fcf8ff",
        dark: "#1b1b23",
        muted: "#464554",
        border: "#e4e1ed",
        subtle: "#f5f2fe",
        "on-error-container": "#93000a",
        "secondary": "#00687a",
        "on-primary": "#ffffff",
        "on-primary-container": "#fffbff",
        "error-container": "#ffdad6",
        "surface-container-high": "#e9e6f3",
        "secondary-fixed": "#acedff",
        "primary-fixed": "#e1e0ff",
        "on-secondary-fixed": "#001f26",
        "inverse-surface": "#303038",
        "tertiary-container": "#b55d00",
        "tertiary-fixed": "#ffdcc5",
        "on-tertiary-fixed-variant": "#703700",
        "surface-container-lowest": "#ffffff",
        "outline": "#767586",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-tertiary-container": "#fffbff",
        "tertiary": "#904900",
        "primary-container": "#6063ee",
        "on-error": "#ffffff",
        "on-surface-variant": "#464554",
        "secondary-fixed-dim": "#4cd7f6",
        "on-surface": "#1b1b23",
        "outline-variant": "#c7c4d7",
        "on-primary-fixed": "#07006c",
        "inverse-primary": "#c0c1ff",
        "on-secondary-container": "#006172",
        "background": "#fcf8ff",
        "on-tertiary": "#ffffff",
        "secondary-container": "#57dffe",
        "surface-tint": "#494bd6",
        "surface-container-low": "#f5f2fe",
        "surface-container-highest": "#e4e1ed",
        "primary-fixed-dim": "#c0c1ff",
        "surface-dim": "#dbd8e4",
        "inverse-on-surface": "#f2effb",
        "on-secondary": "#ffffff",
        "on-background": "#1b1b23",
        "surface-variant": "#e4e1ed",
        "surface-container": "#efecf8",
        "on-secondary-fixed-variant": "#004e5c",
        "tertiary-fixed-dim": "#ffb783",
        "surface-bright": "#fcf8ff",
        "error": "#ba1a1a",
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif']
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fade-in-right': {
          '0%': { opacity: '0', transform: 'translateX(20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'scale-x': {
          '0%': { transform: 'scaleX(0)' },
          '100%': { transform: 'scaleX(1)' },
        }
      },
      animation: {
        'fade-in': 'fade-in 0.3s ease-out',
        'fade-in-right': 'fade-in-right 0.4s cubic-bezier(0.16, 1, 0.3, 1)',
        'scale-x': 'scale-x 0.3s ease-out forwards',
      }
    },
  },
  plugins: [],
}
